<a href="https://colab.research.google.com/github/asnaraliya/ICT/blob/main/Trial_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os

In [1]:
DATA_PATH = "/content/hour.csv"

RAW_DATA_DIR = "raw_data"
REPORTS_DIR = "reports"
OUTPUT_DIR = "output"

In [ ]:
os.makedirs(RAW_DATA_DIR, exist_ok=True)
os.makedirs(REPORTS_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Folders created successfully.")

Folders created successfully.

In [4]:
def extract():

    print("="*50)
    print("EXTRACT STAGE")
    print("="*50)

    df = pd.read_csv(DATA_PATH)

    print(f"\nNumber of Records : {df.shape[0]}")
    print(f"Number of Columns : {df.shape[1]}")

    print("\nColumn Names")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    raw_path = os.path.join(RAW_DATA_DIR, "hour_raw.csv")
    df.to_csv(raw_path, index=False)

    print("\nRaw dataset saved successfully.")

    return df

In [ ]:
df = extract()

df.head()

==================================================
EXTRACT STAGE
==================================================

Number of Records : 17379
Number of Columns : 17

Column Names
['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']

Data Types
instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

Missing Values
instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

Raw dataset saved successfully.

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [ ]:
def transform(df):

    print("=" * 50)
    print("TRANSFORM STAGE")
    print("=" * 50)

    # Check duplicate records
    print("\nDuplicate Records :", df.duplicated().sum())

    # Remove duplicate records
    df.drop_duplicates(inplace=True)

    # Rename columns
    df.rename(columns={
        "instant": "Record_ID",
        "dteday": "Date",
        "yr": "Year",
        "mnth": "Month",
        "hr": "Hour",
        "season": "Season",
        "holiday": "Holiday",
        "weekday": "Weekday",
        "workingday": "Working_Day",
        "weathersit": "Weather",
        "temp": "Temperature",
        "atemp": "Feels_Like_Temperature",
        "hum": "Humidity",
        "windspeed": "Wind_Speed",
        "casual": "Casual_Users",
        "registered": "Registered_Users",
        "cnt": "Total_Rentals"
    }, inplace=True)

    # Convert Date to datetime
    df["Date"] = pd.to_datetime(df["Date"])

    # Convert Month values
    df["Month"] = df["Month"].replace(
        [1,2,3,4,5,6,7,8,9,10,11,12],
        ["January","February","March","April","May","June",
         "July","August","September","October","November","December"]
    )

    # Convert Season values
    df["Season"] = df["Season"].replace(
        [1,2,3,4],
        ["Spring","Summer","Fall","Winter"]
    )

    # Convert Weather values
    df["Weather"] = df["Weather"].replace(
        [1,2,3,4],
        ["Clear","Mist","Light Snow/Rain","Heavy Rain/Snow"]
    )

    # Convert Year values
    df["Year"] = df["Year"].replace(
        [0,1],
        ["2011","2012"]
    )

    # Convert Holiday values
    df["Holiday"] = df["Holiday"].replace(
        [0,1],
        ["No","Yes"]
    )

    # Convert Weekday values
    df["Weekday"] = df["Weekday"].replace(
        [0,1,2,3,4,5,6],
        ["Sunday","Monday","Tuesday","Wednesday",
         "Thursday","Friday","Saturday"]
    )

    # Remove unwanted columns
    df.drop(columns=["Working_Day", "Day_Type"], errors="ignore", inplace=True)

    # Sort records
    df.sort_values(by=["Date", "Hour"], inplace=True)

    # Reset index
    df.reset_index(drop=True, inplace=True)

    # Rearrange columns
    df = df[
        [
            "Record_ID",
            "Date",
            "Month",
            "Year",
            "Hour",
            "Season",
            "Holiday",
            "Weekday",
            "Weather",
            "Temperature",
            "Feels_Like_Temperature",
            "Humidity",
            "Wind_Speed",
            "Casual_Users",
            "Registered_Users",
            "Total_Rentals"
        ]
    ]

    print("\nTransformation Completed Successfully.")
    print("\nTransformed Dataset Preview:")
    print(df.head())

    return df

In [ ]:
df = transform(df)
df.tail(15)

==================================================
TRANSFORM STAGE
==================================================

Duplicate Records : 0

Transformation Completed Successfully.

Transformed Dataset Preview:
   Record_ID       Date    Month  Year  Hour  Season Holiday   Weekday  \
0          1 2011-01-01  January  2011     0  Spring      No  Saturday
1          2 2011-01-01  January  2011     1  Spring      No  Saturday
2          3 2011-01-01  January  2011     2  Spring      No  Saturday
3          4 2011-01-01  January  2011     3  Spring      No  Saturday
4          5 2011-01-01  January  2011     4  Spring      No  Saturday

  Weather  Temperature  Feels_Like_Temperature  Humidity  Wind_Speed  \
0   Clear         0.24                  0.2879      0.81         0.0
1   Clear         0.22                  0.2727      0.80         0.0
2   Clear         0.22                  0.2727      0.80         0.0
3   Clear         0.24                  0.2879      0.75         0.0
4   Clear         0.24                  0.2879      0.75         0.0

   Casual_Users  Registered_Users  Total_Rentals
0             3                13             16
1             8                32             40
2             5                27             32
3             3                10             13
4             0                 1              1

,Record_ID,Date,Month,Year,Hour,Season,Holiday,Weekday,Weather,Temperature,Feels_Like_Temperature,Humidity,Wind_Speed,Casual_Users,Registered_Users,Total_Rentals
17364,17365,2012-12-31,December,2012,9,Spring,No,Monday,Mist,0.18,0.2121,0.64,0.1045,13,144,157
17365,17366,2012-12-31,December,2012,10,Spring,No,Monday,Mist,0.20,0.2121,0.69,0.1343,33,87,120
17366,17367,2012-12-31,December,2012,11,Spring,No,Monday,Mist,0.22,0.2273,0.60,0.1940,43,114,157
17367,17368,2012-12-31,December,2012,12,Spring,No,Monday,Mist,0.24,0.2273,0.56,0.1940,52,172,224
17368,17369,2012-12-31,December,2012,13,Spring,No,Monday,Mist,0.26,0.2576,0.44,0.1642,38,165,203
17369,17370,2012-12-31,December,2012,14,Spring,No,Monday,Mist,0.28,0.2727,0.45,0.2239,62,185,247
17370,17371,2012-12-31,December,2012,15,Spring,No,Monday,Mist,0.28,0.2879,0.45,0.1343,69,246,315
17371,17372,2012-12-31,December,2012,16,Spring,No,Monday,Mist,0.26,0.2576,0.48,0.1940,30,184,214
17372,17373,2012-12-31,December,2012,17,Spring,No,Monday,Mist,0.26,0.2879,0.48,0.0896,14,150,164
17373,17374,2012-12-31,December,2012,18,Spring,No,Monday,Mist,0.26,0.2727,0.48,0.1343,10,112,122
17374,17375,2012-12-31,December,2012,19,Spring,No,Monday,Mist,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,December,2012,20,Spring,No,Monday,Mist,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,December,2012,21,Spring,No,Monday,Clear,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,December,2012,22,Spring,No,Monday,Clear,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,December,2012,23,Spring,No,Monday,Clear,0.26,0.2727,0.65,0.1343,12,37,49

In [8]:
def load(df):

    print("=" * 50)
    print("LOAD STAGE")
    print("=" * 50)

    # Save Cleaned Dataset
    cleaned_path = os.path.join(OUTPUT_DIR, "cleaned_bike_data.csv")
    df.to_csv(cleaned_path, index=False)
    print(f"Cleaned dataset saved: {cleaned_path}")

    # Report 1 - Summary Statistics
    summary = df.describe(include="all")
    summary.to_csv(os.path.join(REPORTS_DIR, "summary_statistics.csv"))

    # Report 2 - Top 10 Records
    df.head(10).to_csv(
        os.path.join(REPORTS_DIR, "top10_records.csv"),
        index=False
    )

    # Report 3 - Bottom 10 Records
    df.tail(10).to_csv(
        os.path.join(REPORTS_DIR, "bottom10_records.csv"),
        index=False
    )

    # Report 4 - Monthly Rental Report
    monthly_report = df.groupby("Month")["Total_Rentals"].sum().reset_index()
    monthly_report.to_csv(
        os.path.join(REPORTS_DIR, "monthly_rental_report.csv"),
        index=False
    )

    # Report 5 - Season-wise Rental Report
    season_report = df.groupby("Season")["Total_Rentals"].sum().reset_index()
    season_report.to_csv(
        os.path.join(REPORTS_DIR, "season_wise_rental_report.csv"),
        index=False
    )

    print("\nAll reports generated successfully.")
    print("\nLoad Stage Completed Successfully.")

In [11]:
def run_etl_pipeline():

    df = extract()
    df = transform(df)
    load(df)

    print("\nETL Pipeline Executed Successfully.")

In [ ]:
if __name__ == "__main__":
    run_etl_pipeline()

==================================================
EXTRACT STAGE
==================================================

Number of Records : 17379
Number of Columns : 17

Column Names
['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']

Data Types
instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

Missing Values
instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

Raw dataset saved successfully.
==================================================
TRANSFORM STAGE
==================================================

Duplicate Records : 0

Transformation Completed Successfully.

Transformed Dataset Preview:
   Record_ID       Date    Month  Year  Hour  Season Holiday   Weekday  \
0          1 2011-01-01  January  2011     0  Spring      No  Saturday
1          2 2011-01-01  January  2011     1  Spring      No  Saturday
2          3 2011-01-01  January  2011     2  Spring      No  Saturday
3          4 2011-01-01  January  2011     3  Spring      No  Saturday
4          5 2011-01-01  January  2011     4  Spring      No  Saturday

  Weather  Temperature  Feels_Like_Temperature  Humidity  Wind_Speed  \
0   Clear         0.24                  0.2879      0.81         0.0
1   Clear         0.22                  0.2727      0.80         0.0
2   Clear         0.22                  0.2727      0.80         0.0
3   Clear         0.24                  0.2879      0.75         0.0
4   Clear         0.24                  0.2879      0.75         0.0

   Casual_Users  Registered_Users  Total_Rentals
0             3                13             16
1             8                32             40
2             5                27             32
3             3                10             13
4             0                 1              1
==================================================
LOAD STAGE
==================================================
Cleaned dataset saved: output/cleaned_bike_data.csv

All reports generated successfully.

Load Stage Completed Successfully.

ETL Pipeline Executed Successfully.